# Site wide configuration

title: Lauren Carley, PhD
email: lauren.n.carley [at] gmail [dot] com
description: >- # this means to ignore newlines until "baseurl:"
  Postdoctoral researcher, University of Minnesota
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icarley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: icarley
orcid: 0000-0003-1911-7025
google:
  plus: #username
  analytics:
  verify:
  scholar: gSyY0jQAAAAJ
